plugins:
  topic_custom_field_enabled:
    default: true
    client: true
  topic_custom_field_name:
    default: 'date_kb_updated'
    client: true
  topic_custom_field_type:
    default: 'string'
    client: true
    type: enum
    choices:
      - string
      - integer
      - boolean
      - json
